name: Pull Requests

on:
  pull_request:
    paths-ignore:
      - '.github/**'

jobs:
  Build:
    uses: tylerbertrand/morphia-workflows/.github/workflows/pull-request.yml@run-clean
    with:
      java: 17
